name: deploy-site
on: 
  push:
    branches:
      - main

jobs:
  cargo-build:
    name: vercel deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
         rust-version: stable

      - name: 'install wasm32-unknown-unknown'
        run: rustup target add wasm32-unknown-unknown

      - uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          version: 'latest'

      - uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'

      - name: build
        run: cd app && trunk build --release -d ../dist

      - uses: amondnet/vercel-action@v20
        with:
          vercel-cli: vercel
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: --prod
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
